// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSA.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TSA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TSADbContext))]
    [Migration("20240423182541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TSA.Core.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDescription");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyEmail");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyPhoneNumber");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyWebsite");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("57f47fdc-5f39-495f-8ca5-e59451b235d7"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uluksar is a company that provides software solutions.",
                            Email = "test@test.com",
                            Name = "Uluksar",
                            PhoneNumber = "+1234567890",
                            Website = "www.uluksar.com"
                        },
                        new
                        {
                            Id = new Guid("6dc31048-5380-4f4e-8329-166a7fa18a60"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Digitalhat is a company that provides software solutions.",
                            Email = "dgtalhat@dgtalhat.com",
                            Name = "Digitalhat",
                            PhoneNumber = "+1234567890",
                            Website = "www.digitalhat.com"
                        },
                        new
                        {
                            Id = new Guid("5e8a27c1-aa20-42b9-85c7-33bd50812581"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ULUARS HOLDING is a company that provides software solutions.",
                            Email = "uluars@uluars.com",
                            Name = "ULUARS HOLDING",
                            PhoneNumber = "+1234567890",
                            Website = "www.uluars.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
