// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSA.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TSA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TSADbContext))]
    partial class TSADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TSA.Core.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyCoverImageUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDescription");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyEmail");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyLogoUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyPhoneNumber");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyWebsite");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7bc7caf-2c92-4ed8-a31e-d1b5f478c701"),
                            CoverImageUrl = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uluksar is a company that provides software solutions.",
                            Email = "test@test.com",
                            LogoUrl = "",
                            Name = "Uluksar",
                            PhoneNumber = "+1234567890",
                            Website = "www.uluksar.com"
                        },
                        new
                        {
                            Id = new Guid("dd0136f3-8eb2-471d-90be-a1be18cfc849"),
                            CoverImageUrl = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Digitalhat is a company that provides software solutions.",
                            Email = "dgtalhat@dgtalhat.com",
                            LogoUrl = "",
                            Name = "Digitalhat",
                            PhoneNumber = "+1234567890",
                            Website = "www.digitalhat.com"
                        },
                        new
                        {
                            Id = new Guid("ce041a71-f3ee-4204-90a6-9dcca8f643e2"),
                            CoverImageUrl = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ULUARS HOLDING is a company that provides software solutions.",
                            Email = "uluars@uluars.com",
                            LogoUrl = "",
                            Name = "ULUARS HOLDING",
                            PhoneNumber = "+1234567890",
                            Website = "www.uluars.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
